import { Providers } from './provider';

import './globals.css';
import { notojp } from '@/styles/fonts';
import Page from '@/components/Page';

export const metadata = {
  title: 'Quiz Factory',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="light">
      <body className={`${notojp.className}`}>
        <Providers>
          <Page>{children}</Page>
        </Providers>
      </body>
    </html>
  );
}
