import './globals.css';
import { kiwi, notojp } from '@/styles/fonts';
import Page from '@/components/Page';
import { Providers } from '@/provider';

export const metadata = {
  title: 'Quiz Factory',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={`${notojp.variable} ${kiwi.variable} light`}>
      <body>
        <Providers>
          <Page>{children}</Page>
        </Providers>
      </body>
    </html>
  );
}
